[package]
name = "wasm_vrf_worker"
version = "0.1.0"
edition = "2021"

[package.metadata.wasm-pack.profile.release]
wasm-opt = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = "0.1"

# VRF and cryptography
vrf-wasm = { version = "0.8.2", features = ["browser"] }
ed25519-dalek = "2.0"
chacha20poly1305 = "0.10"
sha2 = "0.10"
hkdf = "0.12"
base64ct = { version = "1.6", features = ["alloc"] }
serde_json = "1.0"
bincode = "1.3"
rand_core = "0.6"
zeroize = { version = "1.7", features = ["derive"] }
# Async support for Service Worker (using web workers for now)
wasm-bindgen-futures = "0.4"
# Logging dependencies
log = "0.4"
wasm-logger = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]